Include /usr/local/apache/modsecurity-cwaf/domains/*.conf
Include /usr/local/apache/modsecurity-cwaf/rules/*.conf 
Include /usr/local/apache/modsecurity-cwaf/global/*.conf
Include /usr/local/apache/modsecurity-cwaf/custom_user.conf
